name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 120 # Set the job timeout to 2 hours

    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -O ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok/ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: sudo sysctl -w net.ipv4.ip_forward=1
    - name: Create Tunnel
      run: ./ngrok/ngrok.exe tcp 3389

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Expose Local Service with Serveo
      run: |
        ssh -R 80:localhost:3389 serveo.net
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
